from __future__ import annotations

import json
from typing import Protocol

from openai import OpenAI

from .models import IntuneMapping, SuggestedMapping


class LLMClient(Protocol):
    def suggest_mapping(self, mapping: IntuneMapping) -> dict: ...


class HeuristicLLMClient:
    """Default deterministic stub for environments without an LLM provider."""

    def suggest_mapping(self, mapping: IntuneMapping) -> dict:
        return {
            "suggested_implementation_type": "settings_catalog",
            "suggested_intune_area": "Manual Triage",
            "suggested_setting_name": f"Review {mapping.title}",
            "suggested_value": mapping.value,
            "confidence": 0.35,
            "reasoning": "Heuristic fallback generated because no external LLM client was provided.",
        }


class OpenAILLMClient:
    """
    Real OpenAI-backed implementation for manual review suggestion generation.
    """

    def __init__(self, api_key: str, model: str = "gpt-4.1-mini") -> None:
        self.client = OpenAI(api_key=api_key)
        self.model = model

    def suggest_mapping(self, mapping: IntuneMapping) -> dict:
        system_prompt = (
            "You map CIS security controls to Microsoft Intune implementation candidates. "
            "Return only valid JSON with the following keys: "
            "suggested_implementation_type, suggested_intune_area, suggested_setting_name, "
            "suggested_value, confidence, reasoning. "
            "Confidence must be a float between 0.0 and 1.0."
        )

        user_prompt = f"""
CIS control for manual review:

CIS ID: {mapping.cis_id}
Title: {mapping.title}
Implementation type: {mapping.implementation_type}
Intune area: {mapping.intune_area}
Setting name: {mapping.setting_name}
Value: {mapping.value}
Notes: {mapping.notes}
Parsed value type: {mapping.parsed_value_type}
Quality flags: {mapping.quality_flags}

Suggest the best Intune-oriented mapping candidate.
"""

        response = self.client.chat.completions.create(
            model=self.model,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
        )

        content = response.choices[0].message.content or "{}"
        data = json.loads(content)

        return {
            "suggested_implementation_type": data.get("suggested_implementation_type", "settings_catalog"),
            "suggested_intune_area": data.get("suggested_intune_area", "Manual Triage"),
            "suggested_setting_name": data.get("suggested_setting_name", f"Review {mapping.title}"),
            "suggested_value": data.get("suggested_value", mapping.value),
            "confidence": float(data.get("confidence", 0.50)),
            "reasoning": data.get("reasoning", "Generated by OpenAI fallback."),
        }


def suggest_manual_review_mappings(
    mappings: list[IntuneMapping],
    client: LLMClient | None = None,
) -> list[SuggestedMapping]:
    llm = client or HeuristicLLMClient()
    suggestions: list[SuggestedMapping] = []

    for mapping in mappings:
        if mapping.implementation_type != "manual_review":
            continue

        suggestion_data = llm.suggest_mapping(mapping)
        suggestions.append(
            SuggestedMapping(
                cis_id=mapping.cis_id,
                title=mapping.title,
                **suggestion_data,
            )
        )

    return suggestions        suggestion_data = llm.suggest_mapping(mapping)
        suggestions.append(
            SuggestedMapping(
                cis_id=mapping.cis_id,
                title=mapping.title,
                **suggestion_data,
            )
        )

    return suggestions
